### PR TITLE
Removing trace from body when Error happend

### LINKED ISSUE #291: `trace` key is causing jsonld.expand to fetch wrong urls
**API Platform version(s) affected**: 2.1.0

**Description**  
When endpoint returns an error with a trace (DEBUG)
image
image

`getDocumentationUrlFromHeaders` is failing because it's trying to fetch `/api/array` it happens because `_retrieveContextUrls` is visiting all keys and somehow finds this weird endpoint.

### PR DESCRIPTION
**Pull request by oleg-andreyev**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       | fixes #291
| License       | MIT

### CODE REVIEW

File: src/hydra/fetchHydra.js [hunk 1]
```diff
@@ -30,8 +30,11 @@ export default (url, options = {}) => {
     const status = data.response.status;
 
     if (status < 200 || status >= 300) {
+      const body = data.body;
+      delete body.trace;
```
Comment (soyuka) [inline src/hydra/fetchHydra.js:34]: shouldn't we log this though?

Comment (oleg-andreyev) [reply src/hydra/fetchHydra.js:34]: It will be logged by backend + you'll be able to see it in Network Tab, but for Production Mode there won't be any trace

**Comment by soyuka** [comment]
thanks @oleg-andreyev !
