### PR TITLE
Fix infinite Loading progress on React 19

### LINKED ISSUE #598: [Bug] The project has never-ending Loading progress on React 19 (?)
**API Platform version(s) affected**: 4.0.17

**Description**  

We have a complex but well maintained project since 2019. We never have any problem with the major upgrades w/ MUI, react-admin nor w/ the React. But the upgrade to the React 19 and MUI v6 seems impossible. After I solve every errors and breaking changes on console and in the code I got this all the time:

Image

What is happening when this loading page is occurring? What the program waiting for exactly? It seems, the API is reachable and it gives all required information.

Image

or

Image

After a while, I realized that, if I install this project from scratch it fails the same way. I installed as the [docs said](https://api-platform.com/docs/admin/getting-started/). The code can be downloaded below.

[my-admin.zip](https://github.com/user-attachments/files/19094581/my-admin.zip)

I do not know what causing the problem; the react 19 or the MUI v6 or something else.

**How to reproduce**  

1. Install the app by the docs info. 
2. Run the project
3. See the never-ending circular loader...

### PR DESCRIPTION
**Pull request by SebLevDev**
Closes issue #598 - Fix infinite Loading progress on React 19

| Q             | A
| ------------- | ---
| Tickets       | Closes #598
| License       | MIT

### CODE REVIEW

File: src/core/AdminGuesser.tsx [hunk 1]
```diff
@@ -95,6 +96,10 @@ const AdminGuesser = ({
     [setLoading, setIntrospect],
   );
 
+  if (loading) {
+    return React.createElement(Loading, null);
```
Comment (dunglas) [inline src/core/AdminGuesser.tsx:100]: Maybe could we use JSX?

```suggestion
    return <Loading />;
```

**Comment by soyuka** [comment]
thanks @SebLevDev

**Comment by SebLevDev** [comment]
s it possible to publish a release?
